### ISSUE TITLE
Plugin attempts to load nonexistent user guide section.

### ISSUE THREAD

**Issue by jonmoss** [castlegateit/cgit-wp-seo-redux#1]
When viewing the user guide inserted with the cgit-user-guide plugin, the following PHP Notice will be displayed:

Notice: View not found: \public_html\wp-content\plugins\cgit-wp-seo-redux/views/user-guide.php in \public_html\wp-content\plugins\cgit-wp-seo-redux\classes\Cgit\Seo\Renderer.php on line 46

**Comment by johnkhughes** [comment]
Looks like this was fixed last year, so I'm going to close this one.
